spring:
  datasource:
    url: jdbc:h2:file:./data/sentinel;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.sentinel.aml: DEBUG