CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(100) NOT NULL UNIQUE,
    full_name VARCHAR(200) NOT NULL,
    country_code VARCHAR(3) NOT NULL,
    risk_rating VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(100) NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    account_type VARCHAR(40) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    risk_rating VARCHAR(20) NOT NULL,
    opened_on DATE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(100) NOT NULL UNIQUE,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    transaction_type VARCHAR(30) NOT NULL,
    amount DECIMAL(19, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    amount_inr DECIMAL(19, 4) NOT NULL,
    counterparty VARCHAR(200),
    channel VARCHAR(40) NOT NULL,
    jurisdiction VARCHAR(3) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    account_id BIGINT REFERENCES accounts(id),
    rule_code VARCHAR(60) NOT NULL,
    risk_score INTEGER NOT NULL CHECK (risk_score BETWEEN 0 AND 100),
    explanation VARCHAR(1000) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    assigned_to VARCHAR(100),
    disposition_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alert_transactions (
    alert_id BIGINT NOT NULL REFERENCES alerts(id),
    transaction_id BIGINT NOT NULL REFERENCES transactions(id),
    PRIMARY KEY (alert_id, transaction_id)
);

CREATE TABLE cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id BIGINT NOT NULL UNIQUE REFERENCES alerts(id),
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    analyst_id VARCHAR(100) NOT NULL,
    notes VARCHAR(2000),
    disposition VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(60) NOT NULL,
    actor_id VARCHAR(100) NOT NULL,
    details VARCHAR(2000),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_accounts_customer ON accounts(customer_id);
CREATE INDEX idx_transactions_account_time ON transactions(account_id, occurred_at);
CREATE INDEX idx_alerts_status_score ON alerts(status, risk_score);
CREATE INDEX idx_audit_entity ON audit_events(entity_type, entity_id);